### ISSUE TITLE
Better cro trace output for web sockets

### ISSUE THREAD

**Issue by jnthn** [croservices/cro-websocket#1]
Recently, the `trace-output` method was added to `Cro::Message`. We should override it in the web socket frame and message classes in order to do a better job of showing the content.

**Comment by Altai-man** [comment]
Should be fixed with https://github.com/croservices/cro-websocket/commit/6e9cd04314311960b9c6e18c372a3bd3158d5473 and https://github.com/croservices/cro-websocket/commit/dd1dbba28a7a13560a70930236ec6914b52fbe13
Ping if any additional info needs to be added.

**Comment by jnthn** [comment]
Think that'll be sufficient.
