### ISSUE TITLE
Suggestion: client should accept Upgrade header 'WebSocket'

### ISSUE THREAD

**Issue by Demayl** [croservices/cro-websocket#11]
Some websocket servers are using 'WebSocket' instead of 'websocket' token in the Upgrade header.
And maybe a more useful error message here https://github.com/croservices/cro-websocket/blob/addd8866716808b7a9ce010986e9df6acaf2228e/lib/Cro/WebSocket/Client.pm6#L67-L69

See
https://www.iana.org/assignments/http-upgrade-tokens/http-upgrade-tokens.xhtml
https://tools.ietf.org/html/rfc6455#section-11.2

**Comment by Altai-man** [comment]
Thank you for your issue!Yes, you are correct.
Fixing it...

**Comment by Altai-man** [comment]
I believe https://github.com/croservices/cro-websocket/commit/4b11ee906c1aa493e9ec97ab11cbe2fb4e3ea454 makes things a bit nicer with an exception instead of plain error strings and improves checks too.
Please reopen if needed.

**Comment by jnthn** [comment]
@Altai-man That had a logic bug, which I fixed in 4c6034d3ca.
