### ISSUE TITLE
Passing in Authorization or Headers with the Client?

### ISSUE THREAD

**Issue by CurtTilmes** [croservices/cro-websocket#16]
Asked on [StackOverflow](https://stackoverflow.com/questions/52414720/adding-authorization-or-headers-with-crowebsocketclient):

Is there a way to pass in Authorization or Headers with the Client?

**Comment by jnthn** [comment]
No; we should probably have the WebSocket client just pass through various options to the HTTP client.

**Comment by CurtTilmes** [comment]
I didn't realize -- there is already a patch to do this: https://github.com/croservices/cro-websocket/pull/3

**Comment by Altai-man** [comment]
If this patch was merged, should this issue be closed?

**Comment by Altai-man** [comment]
ping @CurtTilmes again.
Can this be closed?

**Comment by CurtTilmes** [comment]
yes. Thank you!
