### ISSUE TITLE
Failing binary message tests on latest Rakudo

### ISSUE THREAD

**Issue by japhb** [croservices/cro-websocket#19]

**Comment by japhb** [comment]
Not sure why I didn't get a chance to enter a description, but trying again.  On latest Rakudo as of 2019-01-12, I get:

===> Testing: Cro::WebSocket:ver<0.8.0>
# Failed test '256 bytes binary message in a single unmasked frame'
# at t/websocket-frame-parser.t line 38
# Failed test '64 KiB binary message in a single unmasked frame'
# at t/websocket-frame-parser.t line 38
# Looks like you failed 2 tests of 44

**Comment by japhb** [comment]
Still occurring on a fresh Rakudo build as of 54fe8a1a.  Output unchanged.

**Comment by Altai-man** [comment]
It was closed with https://github.com/croservices/cro-websocket/commit/c3d3ce8d0db805782ebdca99d485fdf64346b418
and works on Rakudo 2019.03.
