### ISSUE TITLE
`web-socket` blocks continue to work even after server was `exit`ed

### ISSUE THREAD

**Issue by Altai-man** [croservices/cro-websocket#22]
See discussion at https://github.com/croservices/cro-websocket/issues/15
A gist to reproduce the issue: https://gist.github.com/Altai-man/33b94415598ffca6114f7f16c53aa93b

**Comment by jnthn** [comment]
We should write a test before closing this.

**Comment by Altai-man** [comment]
@jnthn does it fixes the gist(server part of it)?

**Comment by jnthn** [comment]
@Altai-man Well, sort of. :-) There was a further `Cro::Core` change https://github.com/croservices/cro-core/commit/edbfdb8fe9468fb2d28c2c8960b07a2efb9f91e2 that was needed too, as well as some further fixes to properly set `$!closed` in the WebSocket client in all the places that it needed to be set.

I put a `CLOSE` in the `supply` block the `web-socket` block returns, and did indeed see it being executed when the server was stopped. In fact, that's probably a good thing to put in a test case.

**Comment by jnthn** [comment]
To be clear, the "sort of" was about whether the commit that initially closed this issue totally fixed it. I believe with all of the commits I did last night taken together, the issues in the gist are fully fixed.

**Comment by Altai-man** [comment]
Test added at https://github.com/croservices/cro-websocket/commit/d005c3b1e50ff5a4d44c3662d4ef8308d512803e
